from pydantic import BaseModel
# 2. Class which describes Bank Notes measurements
class mentalhealth(BaseModel):
    Q1A: str
    Q2A: str
    Q3A: str
    Q4A: str
    Q5A: str 
    Q6A: str
    Q7A: str 
    Q8A: str
    Q9A: str 
    Q10A: str
    Q11A: str 
    Q12A: str
    Q13A: str 
    Q14A: str
    Q15A: str 
    Q16A: str
    Q17A: str 
    Q18A: str
    Q19A: str 
    Q20A: str
    Q21A: str 
    Q22A: str
    Q23A: str 
    Q24A: str
    Q25A: str 
    Q26A: str
    Q27A: str 
    Q28A: str
    Q29A: str 
    Q30A: str
    Q31A: str 
    Q32A: str
    Q33A: str 
    Q34A: str
    Q35A: str 
    Q36A: str
    Q37A: str 
    Q38A: str
    Q39A: str 
    Q40A: str
    Q41A: str 
    Q42A: str
    TIPI1: str
    TIPI2: str
    TIPI3: str
    TIPI4: str
    TIPI5: str
    TIPI6: str
    TIPI7: str
    TIPI8: str
    TIPI9: str
    TIPI10: str
    education:str
    urban: str
    gender: str
    age: str
    religion: str
    race:str
    married:str
    familysize: str